export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const STORE_USER_INFO = 'STORE_USER_INFO';

export const GET_USER_FETCHING = 'GET_USER_FETCHING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const CHART_PIN_REQUEST = "CHART_PIN_REQUEST";
export const CHART_PIN_SUCCESS = "CHART_PIN_SUCCESS";
export const CHART_PIN_FAILURE = "CHART_PIN_FAILURE";

export const USER_STORE_REQUEST = "USER_STORE_REQUEST";
export const USER_STORE_SUCCESS = "USER_STORE_SUCCESS";
export const USER_STORE_FAILURE = "USER_STORE_FAILURE";